server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: mototrace-api
            uri: http://${ROUTE_HOST_MOTOTRACE_API:localhost}:8091/api/v1
            predicates:
              - Path=/mototrace-api/**
            filters:
              - RewritePath=/mototrace-api/?(?<segment>.*), /${segment}
          - id: worker-position
            uri: http://${ROUTE_HOST_WORKER_POSITION:localhost}:8092/api/v1
            predicates:
              - Path=/worker-position/**
            filters:
              - RewritePath=/worker-position/?(?<segment>.*), /${segment}