services:
  mototrace-app:
    build:
      context: mototrace-app
    container_name: mototrace-app
    ports:
      - "8080:80"
  
  gateway-api:
    build:
      context: gateway-api
    container_name: gateway-api
    restart: always
    ports:
      - "8090:8090"

  mototrace-api:
    build:
      context: mototrace-api
    container_name: mototrace-api
    restart: always
    ports:
      - "8091:8091"
    depends_on:
      postgres:
        condition: service_started

  worker-position:
    build:
      context: worker-position
    container_name: worker-position
    restart: always
    ports:
      - "8092:8092"
    depends_on:
      mongodb:
        condition: service_started

  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mototrace
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - mototrace-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      TZ: America/Sao_Paulo
    ports:
      - "27017:27017"

volumes:
  mototrace-data:
